- block:
  - debug:
      var: user

  - name: authorized_keys | Set up pub keys for users
    authorized_key:
      user:  "{{ item.0.name }}"
      key:   "{{ lookup('file', item.1.src | default(item.1)) }}"
      path:  "/home/{{ item.0.name + '/' + (item.1.ssh.path | default('.ssh')) }}/authorized_keys"
      state: "{{ item.1.state | default('present') }}"
    with_subelements:
      - "{{ user }}"
      - ssh.autorized_keys
      - skip_missing: true

  tags: ssh_authorized_keys
