- block:
  - name: authorized_keys | set up pub keys for users
    authorized_key:
      user:  "{{ item.0.owner }}"
      key:   "{{ lookup('file', item.0.src) }}"
      path:  "/home/{{ item.0.owner + '/' + (item.1.path | default('.ssh')) }}/authorized_keys"
      state: "{{ item.0.state | default('present') }}"
    when:
      - ssh_authorized_keys | length
      - item.0.owner == item.1.owner
    with_nested:
      - "{{ ssh_authorized_keys }}"
      - "{{ ssh_user }}"

  tags: ssh_authorized_keys
