- block:
  - name: client_config | template > generate openssh-client config
    template:
      src:   ssh_config.j2
      dest:  "/home/{{ item.owner + '/' + (item.path | default('.ssh')) }}/config"
      owner: "{{ item.owner }}"
      group: "{{ item.group | default(omit) }}"
      mode:  "0600"
    when: ssh_client_config | length
    loop: "{{ ssh_user }}"

  tags: ssh_client_config, ssh_client
