- block:
  - import_tasks: set_fact.yml

  - import_tasks: packages.yml

  - import_tasks: sshd_config.yml

  - import_tasks: generate_keys.yml

  - import_tasks: client_dirs.yml

  - import_tasks: client_config.yml

#   - import_tasks: private_keys.yml

#   # - import_tasks: public_keys.yml   # KO, faire comme private_keys.yml

#   - import_tasks: authorized_keys.yml

#   # - import_tasks: known_hosts.yml     ## todo

  become_user: root
  tags: ssh
