- block:
  - name: packages | package > install dependencies
    package:
      name: "{{ item }}"
    loop: "{{ ssh.packages }}"

  - name: packages | aur > install sshs
    aur:
      name: "{{ item }}"
    with_items:
      - sshs
    when:
      - ansible_distribution == "Archlinux"
      - ansible_architecture != "aarch64"
      - ansible_play_name    != "chroot"
      - aur_user | length
    become_user: "{{ aur_user }}"

  tags: ssh_packages
