- block:
  - name: private_keys | copy > Private keys
    copy:
      src:   "{{ item.1.src | default(item.1) }}"
      dest:  "/home/{{ item.0.name + '/' + (item.0.ssh.path | default('.ssh')) }}"
      owner: "{{ item.0.name }}"
      group: "{{ item.0.group | default(item.0.name) }}"
      mode:  "0600"
    when:
      - item.1.state is undefined or item.1.state == "present"
      - inventory_hostname != "chroot"
    with_subelements:
      - "{{ user }}"
      - ssh.private_keys
      - skip_missing: true

  - name: private_keys | file > remove private keys
    file:
      path:  "/home/{{ item.0.name + '/' + (item.0.ssh.path | default('.ssh')) + '/' + (item.1.src | basename) }}"
      state: absent
    when:
      - item.1.state is defined
      - item.1.state == "absent"
    with_subelements:
      - "{{ user }}"
      - ssh.private_keys
      - skip_missing: true
    tags: ssh_private_keys_remove

  tags: ssh_private_keys
