- block:
  - name: public_keys | copy > Public keys
    copy:
      src:   "{{ item.1.src | default(item.1) }}"
      dest:  "/home/{{ item.0.name + '/' + (item.0.ssh.path | default('.ssh')) }}"
      owner: "{{ item.0.name }}"
      group: "{{ item.0.group | default(item.0.name) }}"
      mode:  "0600"
    when:
      - item.1.state is undefined or item.1.state == "present"
    with_subelements:
      - "{{ user }}"
      - ssh.public_keys
      - skip_missing: true
    tags: ssh_public_keys_add

  - name: public_keys | file > Remove public keys
    file:
      path:  "/home/{{ item.0.name + '/' + (item.0.ssh.path | default('.ssh')) + '/' + (item.1.src | basename) }}"
      state: absent
    when:
      - item.1.state is defined
      - item.1.state == "absent"
    with_subelements:
      - "{{ user }}"
      - ssh.public_keys
      - skip_missing: true
    tags: ssh_public_keys_remove

  tags: ssh_public_keys
