- block:
  - name: sshd_config | template > generate banner
    template:
      src:    banner.j2
      dest:   "{{ sshd_banner_path }}"
      owner:  root
      group:  "{{ sshd.config.group }}"
      mode:   "0664"
    when: sshd_banner_msg | length

  - name: sshd_config | template > generate sshd_config
    template:
      src:   sshd_config.j2
      dest:  "{{ sshd.config.path }}"
      owner: "{{ sshd.config.owner }}"
      group: "{{ sshd.config.group }}"
      mode:  "0600"
    notify: "handler | service > restart sshd"

  - name: sshd_config | service > start and enable sshd
    service:
      name:    "{{ sshd.service }}"
      state:   started
      enabled: yes
    # when: ansible_play_name != "chroot"     ## even if warning, need it to enable service

  tags: sshd_config
